#ifndef SV_MAJORNUMBER
#  define SV_MAJORNUMBER          0
#endif
#ifndef SV_MINORNUMBER
#  define SV_MINORNUMBER          0
#endif
#ifndef SV_BUILDNUMBER
#  define SV_BUILDNUMBER          0
#endif
#ifndef SV_MODIFICATIONNUMBER
#  define SV_MODIFICATIONNUMBER   1
#endif
#ifndef SV_BUILDEXT
#  define SV_BUILDEXT             "variousDebug"
#endif
#ifndef SV_DATEYEAR
#  define SV_DATEYEAR             2014
#endif
#ifndef SV_DATEMONTH
#  define SV_DATEMONTH            12
#endif
#ifndef SV_DATEDAY
#  define SV_DATEDAY              31
#endif

// don't forget empty end line:
  
