######################################################################
# Automatically generated by qmake (2.01a) mar. juin 19 09:36:28 2012
######################################################################

TEMPLATE = lib
CONFIG = staticlib
TARGET = Utils 
INCLUDEPATH += .

# Input
HEADERS += utils.h
SOURCES += utils.cpp
