######################################################################
# Automatically generated by qmake (2.01a) mar. juin 19 09:36:06 2012
######################################################################

TEMPLATE = app
TARGET = SAMPLE 
DEPENDPATH += . ..
INCLUDEPATH += . ..
LIBS += -L$$OUT_PWD/../utils -lUtils
DEFINES += UTILS_IMPORT

# Input
SOURCES += main.cpp
