######################################################################
# Automatically generated by qmake (2.01a) mar. juin 19 09:36:16 2012
######################################################################

TEMPLATE = app
TARGET = SAMPLE-PROJECT-TESTS 
CONFIG += qtestlib
DEPENDPATH += . ..
INCLUDEPATH += . ..
LIBS += -L$$OUT_PWD/../utils -lUtils
DEFINES += UTILS_IMPORT

# Input
HEADERS += SAMPLE-test.h
SOURCES += main.cpp SAMPLE-test.cpp
